version: "3"
networks:
  kudu-net:
    driver: bridge

services:
  kudu-master-1:
    image: apache/kudu:${KUDU_QUICKSTART_VERSION:-latest}
    ports:
      - "7051:7051"
      - "8051:8051"
    command: ["master"]
    networks:
      - kudu-net
    volumes:
      - kudu-master-1:/var/lib/kudu
    environment:
      - KUDU_MASTERS=kudu-master-1:7051,kudu-master-2:7151
      #- KUDU_MASTERS=kudu-master-1:7051,kudu-master-2:7151,kudu-master-3:7251
      # TODO: Use `0.0.0.0` instead of 0.0.0.0 when it
      # works on Linux (https://github.com/docker/for-linux/issues/264)
      - >
        MASTER_ARGS=--fs_wal_dir=/var/lib/kudu/master --rpc_bind_addresses=kudu-master-1:7051 --rpc_advertised_addresses=kudu-master-1:7051 --webserver_port=8051 --webserver_advertised_addresses=kudu-master-1:8051 --webserver_doc_root=/opt/kudu/www --stderrthreshold=0 --unlock_unsafe_flags 
  kudu-master-2:
    image: apache/kudu:${KUDU_QUICKSTART_VERSION:-latest}
    ports:
      - "7151:7151"
      - "8151:8151"
    command: ["master"]
    networks:
      - kudu-net
    volumes:
      - kudu-master-2:/var/lib/kudu
    environment:
      - KUDU_MASTERS=kudu-master-1:7051,kudu-master-2:7151
     # - KUDU_MASTERS=kudu-master-1:7051,kudu-master-2:7151,kudu-master-3:7251
      - >
        MASTER_ARGS=--fs_wal_dir=/var/lib/kudu/master --rpc_bind_addresses=kudu-master-2:7151 --rpc_advertised_addresses=kudu-master-2:7151 --webserver_port=8151 --webserver_advertised_addresses=kudu-master-2:8151 --webserver_doc_root=/opt/kudu/www --stderrthreshold=0 --unlock_unsafe_flags 
#  kudu-master-3:
#    image: apache/kudu:${KUDU_QUICKSTART_VERSION:-latest}
#    ports:
#      - "7251:7251"
#      - "8251:8251"
#    command: ["master"]
#    networks:
#       - kudu-net
#    volumes:
#      - kudu-master-3:/var/lib/kudu
#    environment:
#      - KUDU_MASTERS=kudu-master-1:7051,kudu-master-2:7151,kudu-master-3:7251
#      - >
#        MASTER_ARGS=--fs_wal_dir=/var/lib/kudu/master --rpc_bind_addresses=kudu-master-3:7251 --rpc_advertised_addresses=kudu-master-3:7251 --webserver_port=8251 --webserver_advertised_addresses=kudu-master-3:8251 --webserver_doc_root=/opt/kudu/www --stderrthreshold=0 --unlock_unsafe_flags 

  kudu-tserver-1:
    image: apache/kudu:${KUDU_QUICKSTART_VERSION:-latest}
    depends_on:
      - kudu-master-1
      - kudu-master-2
#      - kudu-master-3
    ports:
      - "7050:7050"
      - "8050:8050"
    command: ["tserver"]
    networks:
      - kudu-net
    volumes:
      - kudu-tserver-1:/var/lib/kudu
    environment:
      - KUDU_MASTERS=kudu-master-1:7051,kudu-master-2:7151
     # - KUDU_MASTERS=kudu-master-1:7051,kudu-master-2:7151,kudu-master-3:7251
      - >
        TSERVER_ARGS=--fs_wal_dir=/var/lib/kudu/tserver --rpc_bind_addresses=kudu-tserver-1:7050 --rpc_advertised_addresses=kudu-tserver-1:7250 --webserver_port=8050 --webserver_advertised_addresses=kudu-tserver-1:8050 --webserver_doc_root=/opt/kudu/www --stderrthreshold=0 --unlock_unsafe_flags  
  kudu-tserver-2:
    image: apache/kudu:${KUDU_QUICKSTART_VERSION:-latest}
    depends_on:
      - kudu-master-1
      - kudu-master-2
#      - kudu-master-3
    ports:
      - "7150:7150"
      - "8150:8150"
    command: ["tserver"]
    networks:
      - kudu-net
    volumes:
      - kudu-tserver-2:/var/lib/kudu
    environment:
      - KUDU_MASTERS=kudu-master-1:7051,kudu-master-2:7151
#      - KUDU_MASTERS=kudu-master-1:7051,kudu-master-2:7151,kudu-master-3:7251
      - >
        TSERVER_ARGS=--fs_wal_dir=/var/lib/kudu/tserver --rpc_bind_addresses=kudu-tserver-2:7150 --rpc_advertised_addresses=kudu-tserver-2:7150 --webserver_port=8150 --webserver_advertised_addresses=kudu-tserver-2:8150 --webserver_doc_root=/opt/kudu/www --stderrthreshold=0 --unlock_unsafe_flags
#  kudu-tserver-3:
#    image: apache/kudu:${KUDU_QUICKSTART_VERSION:-latest}
#    depends_on:
#      - kudu-master-1
#      - kudu-master-2
#      - kudu-master-3
#    ports:
#      - "7250:7250"
#      - "8250:8250"
#    command: ["tserver"]
#    networks:
#      - kudu-net
#    volumes:
#      - kudu-tserver-3:/var/lib/kudu
#    environment:
#      - KUDU_MASTERS=kudu-master-1:7051,kudu-master-2:7151,kudu-master-3:7251
#      - >
#        TSERVER_ARGS=--fs_wal_dir=/var/lib/kudu/tserver --rpc_bind_addresses=kudu-tserver-3:7250 --rpc_advertised_addresses=kudu-tserver-3:7250 --webserver_port=8250 --webserver_advertised_addresses=kudu-tserver-3:8250 --webserver_doc_root=/opt/kudu/www --stderrthreshold=0 --unlock_unsafe_flags
#  kudu-tserver-4:
#    image: apache/kudu:${KUDU_QUICKSTART_VERSION:-latest}
#    depends_on:
#      - kudu-master-1
#      - kudu-master-2
#      - kudu-master-3
#    ports:
#      - "7350:7350"
#      - "8350:8350"
#    command: ["tserver"]
#    networks:
#      - kudu-net
#    volumes:
#      - kudu-tserver-4:/var/lib/kudu
#    environment:
#      - KUDU_MASTERS=kudu-master-1:7051,kudu-master-2:7151,kudu-master-3:7251
#      - >
#        TSERVER_ARGS=--fs_wal_dir=/var/lib/kudu/tserver--rpc_bind_addresses=kudu-tserver-4:7350 --rpc_advertised_addresses=kudu-tserver-4:7350 --webserver_port=8350 --webserver_advertised_addresses=kudu-tserver-4:8350 --webserver_doc_root=/opt/kudu/www --stderrthreshold=0 --unlock_unsafe_flags 
#  kudu-tserver-5:
#    image: apache/kudu:${KUDU_QUICKSTART_VERSION:-latest}
#    depends_on:
#      - kudu-master-1
#      - kudu-master-2
#      - kudu-master-3
#    ports:
#      - "7450:7450"
#      - "8450:8450"
#    command: ["tserver"]
#    networks:
#      - kudu-net
#    volumes:
#      - kudu-tserver-5:/var/lib/kudu
#    environment:
#      - KUDU_MASTERS=kudu-master-1:7051,kudu-master-2:7151,kudu-master-3:7251
#      - >
#       TSERVER_ARGS=--fs_wal_dir=/var/lib/kudu/tserver --rpc_bind_addresses=kudu-tserver-5:7450 --rpc_advertised_addresses=kudu-tserver-5:7450 --webserver_port=8450 --webserver_advertised_addresses=kudu-tserver-5:8450 --webserver_doc_root=/opt/kudu/www --stderrthreshold=0 --unlock_unsafe_flags

  kuduimpala:
    image: apache/kudu:impala-latest
    ports:
      - "21000:21000"
      - "21050:21050"
      - "25000:25000"
      - "25010:25010"
      - "25020:25020"
    command: ["impala"]
    networks:
      - kudu-net
    depends_on:
      - kudu-master-1
      - kudu-master-2
#      - kudu-master-3
    environment:
      - KUDU_MASTERS=kudu-master-1:7051,kudu-master-2:7151,kudu-master-3:7251
  kudu-hue:
    image: gethue/hue:latest
    networks:
      - kudu-net
    ports:
      - "8888:8888"
#    command: /data/application/startup.sh
    depends_on:
      - kuduimpala
      - kudu-mysql
    volumes:
      - ./conf/hue.ini:/usr/share/hue/desktop/conf/z-hue.ini
#      - ./conf/startup_hue.sh:/data/application/startup.sh
  kudu-mysql:
      image: mysql:latest
      ports:
          - "3320:3306"
      command: --init-file /data/application/init.sql
      networks:
        - kudu-net
      volumes:
          - kudu-metadata:/var/lib/mysql
          - ./conf/init.sql:/data/application/init.sql
      environment:
          MYSQL_ROOT_USER: root
#          MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
#          MYSQL_ROOT_PASSWORD: secret
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: hue
          MYSQL_USER: hue
          MYSQL_PASSWORD: huepassword
volumes:
  kudu-master-1:
  kudu-master-2:
#  kudu-master-3:
  kudu-tserver-1:
  kudu-tserver-2:
#  kudu-tserver-3:
#  kudu-tserver-4:
#  kudu-tserver-5:
  kudu-metadata:
